
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9E8B9AD3F4C6F76351F4C9AC4D3056A0'
    
_lr_action_items = {'COMMA':([51,53,55,56,57,58,59,71,72,73,89,90,95,101,],[-20,74,-28,-31,-32,-30,77,-25,-24,-22,-23,-21,-29,-26,]),'WHERE':([33,42,],[40,49,]),'RPAREN':([51,53,55,56,57,58,59,71,72,73,89,90,91,94,95,97,101,105,106,],[-20,75,-28,-31,-32,-30,78,-25,-24,-22,-23,-21,98,100,-29,101,-26,106,-27,]),'PRIMARY':([74,],[92,]),'FROM':([18,27,],[26,34,]),'INDEX':([9,21,],[22,29,]),'GE':([47,],[68,]),'INTO':([15,],[25,]),'UNIQUE':([71,72,73,101,],[-25,-24,89,-26,]),'DROP':([0,],[9,]),'AND':([46,48,56,57,58,69,79,80,81,82,83,84,85,86,],[61,-35,-31,-32,-30,61,-37,-36,-38,-39,-42,-43,-40,-41,]),'ICONST':([45,63,64,65,66,67,68,77,88,],[58,58,58,58,58,58,58,58,97,]),'FLOAT':([52,],[71,]),'EQ':([47,],[67,]),'GT':([47,],[63,]),'ON':([36,],[44,]),'CHAR':([52,],[70,]),'DELETE':([0,],[18,]),'SEMICOLON':([12,30,31,33,42,46,48,56,57,58,69,75,78,79,80,81,82,83,84,85,86,98,100,],[24,37,38,41,50,62,-35,-31,-32,-30,87,93,96,-37,-36,-38,-39,-42,-43,-40,-41,102,104,]),'STAR':([19,],[27,]),'ID':([22,23,25,26,28,29,34,40,43,44,49,60,61,74,76,103,],[30,31,32,33,35,36,42,47,52,54,47,47,47,52,94,105,]),'SELECT':([0,],[19,]),'INSERT':([0,],[15,]),'FCONST':([45,63,64,65,66,67,68,77,],[56,56,56,56,56,56,56,56,]),'NE':([47,],[66,]),'$end':([1,2,3,4,5,6,7,8,10,11,13,14,16,17,20,24,37,38,41,50,62,87,93,96,102,104,],[-15,0,-4,-2,-10,-8,-11,-3,-7,-5,-6,-12,-14,-13,-1,-16,-47,-46,-44,-33,-45,-34,-17,-9,-18,-19,]),'QUIT':([0,],[12,]),'KEY':([92,],[99,]),'LT':([47,],[64,]),'LPAREN':([35,39,54,70,99,],[43,45,76,88,103,]),'TABLE':([9,21,],[23,28,]),'SCONST':([45,63,64,65,66,67,68,77,],[57,57,57,57,57,57,57,57,]),'OR':([46,48,56,57,58,69,79,80,81,82,83,84,85,86,],[60,-35,-31,-32,-30,60,-37,-36,-38,-39,-42,-43,-40,-41,]),'INT':([52,],[72,]),'VALUES':([32,],[39,]),'LE':([47,],[65,]),'CREATE':([0,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'column':([43,74,],[51,90,]),'drop_index':([0,],[1,]),'sql_statement':([0,],[2,]),'drop_table':([0,],[16,]),'insert_statement':([0,],[4,]),'select_all':([0,],[5,]),'create_index':([0,],[6,]),'column_type':([52,],[73,]),'conditional_select':([0,],[7,]),'select_statement':([0,],[8,]),'create_table':([0,],[10,]),'value_list':([45,],[59,]),'drop_statement':([0,],[11,]),'create_statement':([0,],[20,]),'value':([45,63,64,65,66,67,68,77,],[55,81,82,83,84,85,86,95,]),'quit_statement':([0,],[13,]),'conditions':([40,49,],[46,69,]),'delete_all':([0,],[14,]),'delete_statement':([0,],[3,]),'primary_clause':([74,],[91,]),'conditional_delete':([0,],[17,]),'condition':([40,49,60,61,],[48,48,79,80,]),'column_list':([43,],[53,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sql_statement","S'",1,None,None,None),
  ('sql_statement -> create_statement','sql_statement',1,'p_sql_statement','interpreter.py',95),
  ('sql_statement -> insert_statement','sql_statement',1,'p_sql_statement','interpreter.py',96),
  ('sql_statement -> select_statement','sql_statement',1,'p_sql_statement','interpreter.py',97),
  ('sql_statement -> delete_statement','sql_statement',1,'p_sql_statement','interpreter.py',98),
  ('sql_statement -> drop_statement','sql_statement',1,'p_sql_statement','interpreter.py',99),
  ('sql_statement -> quit_statement','sql_statement',1,'p_sql_statement','interpreter.py',100),
  ('create_statement -> create_table','create_statement',1,'p_create_statement','interpreter.py',107),
  ('create_statement -> create_index','create_statement',1,'p_create_statement','interpreter.py',108),
  ('insert_statement -> INSERT INTO ID VALUES LPAREN value_list RPAREN SEMICOLON','insert_statement',8,'p_insert_statement','interpreter.py',125),
  ('select_statement -> select_all','select_statement',1,'p_select_statement','interpreter.py',137),
  ('select_statement -> conditional_select','select_statement',1,'p_select_statement','interpreter.py',138),
  ('delete_statement -> delete_all','delete_statement',1,'p_delete_statement','interpreter.py',155),
  ('delete_statement -> conditional_delete','delete_statement',1,'p_delete_statement','interpreter.py',156),
  ('drop_statement -> drop_table','drop_statement',1,'p_drop_statement','interpreter.py',172),
  ('drop_statement -> drop_index','drop_statement',1,'p_drop_statement','interpreter.py',173),
  ('quit_statement -> QUIT SEMICOLON','quit_statement',2,'p_quit_statement','interpreter.py',192),
  ('create_table -> CREATE TABLE ID LPAREN column_list RPAREN SEMICOLON','create_table',7,'p_create_table','interpreter.py',201),
  ('create_table -> CREATE TABLE ID LPAREN column_list COMMA primary_clause RPAREN SEMICOLON','create_table',9,'p_create_table','interpreter.py',202),
  ('create_index -> CREATE INDEX ID ON ID LPAREN ID RPAREN SEMICOLON','create_index',9,'p_create_index','interpreter.py',219),
  ('column_list -> column','column_list',1,'p_column_list','interpreter.py',232),
  ('column_list -> column_list COMMA column','column_list',3,'p_column_list','interpreter.py',233),
  ('column -> ID column_type','column',2,'p_column','interpreter.py',245),
  ('column -> ID column_type UNIQUE','column',3,'p_column','interpreter.py',246),
  ('column_type -> INT','column_type',1,'p_column_type','interpreter.py',256),
  ('column_type -> FLOAT','column_type',1,'p_column_type','interpreter.py',257),
  ('column_type -> CHAR LPAREN ICONST RPAREN','column_type',4,'p_column_type','interpreter.py',258),
  ('primary_clause -> PRIMARY KEY LPAREN ID RPAREN','primary_clause',5,'p_primary_clause','interpreter.py',271),
  ('value_list -> value','value_list',1,'p_value_list','interpreter.py',279),
  ('value_list -> value_list COMMA value','value_list',3,'p_value_list','interpreter.py',280),
  ('value -> ICONST','value',1,'p_value','interpreter.py',292),
  ('value -> FCONST','value',1,'p_value','interpreter.py',293),
  ('value -> SCONST','value',1,'p_value','interpreter.py',294),
  ('select_all -> SELECT STAR FROM ID SEMICOLON','select_all',5,'p_select_all','interpreter.py',302),
  ('conditional_select -> SELECT STAR FROM ID WHERE conditions SEMICOLON','conditional_select',7,'p_conditional_select','interpreter.py',312),
  ('conditions -> condition','conditions',1,'p_conditions','interpreter.py',323),
  ('conditions -> conditions AND condition','conditions',3,'p_conditions','interpreter.py',324),
  ('conditions -> conditions OR condition','conditions',3,'p_conditions','interpreter.py',325),
  ('condition -> ID GT value','condition',3,'p_condition','interpreter.py',338),
  ('condition -> ID LT value','condition',3,'p_condition','interpreter.py',339),
  ('condition -> ID EQ value','condition',3,'p_condition','interpreter.py',340),
  ('condition -> ID GE value','condition',3,'p_condition','interpreter.py',341),
  ('condition -> ID LE value','condition',3,'p_condition','interpreter.py',342),
  ('condition -> ID NE value','condition',3,'p_condition','interpreter.py',343),
  ('delete_all -> DELETE FROM ID SEMICOLON','delete_all',4,'p_delete_all','interpreter.py',352),
  ('conditional_delete -> DELETE FROM ID WHERE conditions SEMICOLON','conditional_delete',6,'p_conditional_delete','interpreter.py',362),
  ('drop_table -> DROP TABLE ID SEMICOLON','drop_table',4,'p_drop_table','interpreter.py',374),
  ('drop_index -> DROP INDEX ID SEMICOLON','drop_index',4,'p_drop_index','interpreter.py',384),
]
